
BEGIN
   LINK_COMICDB.Add_Links;
   LINK_COMICDB.Find_ComicDB_Matches('%X%Men%20%', 2013, 80, 'Y');
END;
/


SELECT   Title, Volume, Count(*)
FROM     V_MISSING_COMICDB_COMIC
GROUP BY Title, Volume
ORDER BY Count(*) Desc, Title, Volume
/
SELECT * FROM V_MISSING_COMICDB_COMIC
WHERE  Title Like 'W%%'
--WHERE    upper(Title) LIKE '%%DEATH%MATE%' --AND Issue BETWEEN 522 AND 524
/

SELECT * FROM V_DIGITAL_AND_COMICDB_COMIC_SUMMARY_DETAILS
WHERE    upper(Title) LIKE '%VAMPIRELLA%%' -- AND Issue BETWEEN 64 AND 66
ORDER BY Volume, Src, Title
/

SELECT * FROM V_DIGITAL_AND_COMICDB_COMIC_DETAILS
WHERE    upper(Title) LIKE 'X%MEN%19%' -- AND Issue BETWEEN 222 AND 227

/

