

CREATE GLOBAL TEMPORARY TABLE GS_GT_COMBINATION_SEQUENCE (
  Pattern_Id           NUMBER,
  Combination_Id       NUMBER,
  Prev_Combination_Id  NUMBER,
  Sequence_No          NUMBER,
  Start_Pos            NUMBER,
  End_Pos              NUMBER)
ON COMMIT DELETE ROWS
/

CREATE INDEX IDX_GT_CS_COMB_ID ON GS_GT_COMBINATION_SEQUENCE (COMBINATION_ID);
CREATE INDEX IDX_GT_CS_PATT_ID ON GS_GT_COMBINATION_SEQUENCE (PATTERN_ID);
