

CREATE TABLE GS_COMBINATION_SEQUENCE (
  Combination_Id       NUMBER,
  Start_Pos            NUMBER,
  End_Pos              NUMBER)
/

CREATE INDEX IDX_CS_COMB_ID ON GS_COMBINATION_SEQUENCE (COMBINATION_ID);
