

Drop   Table ABBREVIATED_WORD_SPLIT Purge
/

Create Table ABBREVIATED_WORD_SPLIT (
Abbreviated_Word Varchar2(200),
Split_Words      Varchar2(200)
)
/

INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('THERE''D', 'THERE HAD'); 
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('I''D',     'I HAD');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HE''D',    'HE HAD');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('YOU''D',   'YOU HAD');
--
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('AIN''T',     'AM NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WEREN''T',   'WERE NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CAN''T',     'CAN NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MAYN''T',    'MAY NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SHOULDN''T', 'SHOULD NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WARN''T',    'WAS NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DON''T',     'DO NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WOULDN''T',  'WOULD NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DIDN''T',    'DID NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WASN''T',    'WAS NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WON''T',     'WILL NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HADN''T',    'HAD NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('COULDN''T',  'COULD NOT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DOESN''T',   'DOES NOT');
--
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('I''M',     'I AM');
--
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('YOUR''N',   'YOURS');
--
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LET''S',  'LET US');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('IT''S',   'IT IS');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('THAT''S', 'THAT IS');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HERE''S', 'HERE IS');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WHO''S',  'WHO IS');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WOT''S',  'WHAT IS');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HE''S',   'HE IS');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('THERE''S','THERE IS');
--
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('UN''S', 'ONES');
--
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CLY''S',        'CLY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SHOOTER''S',    'SHOOTER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('FATHER''S',     'FATHER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('ANYBODY''S',    'ANYBODY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LEGISLATION''S','LEGISLATION');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('NIGHT''S',      'NIGHT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('STUDENT''S',    'STUDENT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CRIMINAL''S',   'CRIMINAL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GORGON''S',     'GORGON');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CHATEAU''S',    'CHATEAU');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GABELLE''S',    'GABELLE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GASPARD''S',    'GASPARD');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('FORTNIGHT''S',  'FORTNIGHT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SAINT''S',      'SAINT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('RIVER''S',      'RIVER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DRAGON''S',     'DRAGON');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LUCIFER''S',    'LUCIFER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('PALUS''S',      'PALUS');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SHIP''S',       'SHIP');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('UNCLE''S',      'UNCLE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LIEUTENANT''S', 'LIEUTENANT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('COURT''S',      'COURT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SISTER''S',     'SISTER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CHEMIST''S',    'CHEMIST');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WEARER''S',     'WEARER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('BAKER''S',      'BAKER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MASTER''S',     'MASTER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CARTON''S',     'CARTON');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LUCIE''S',      'LUCIE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('PROSS''S',      'PROSS');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HUSBAND''S',    'HUSBAND');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('BAD''S',        'BAD');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CROWD''S',      'CROWD');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SOMEBODY''S',   'SOMEBODY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DRUM''S',       'DRUM');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('BULL''S',       'BULL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GOD''S',        'GOD');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CITIZEN''S',    'CITIZEN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MORROW''S',     'MORROW');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('TELLSON''S',    'TELLSON');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GENTLEMAN''S',  'GENTLEMAN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HEAVEN''S',     'HEAVEN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GUNMAKER''S',   'GUNMAKER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GAOLER''S',     'GAOLER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('KING''S',       'KING');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DAY''S',        'DAY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LADYBIRD''S',   'LADYBIRD');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('TRADESMAN''S',  'TRADESMAN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DUNSTAN''S',    'DUNSTAN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HALF''S',       'HALF');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('BARSAD''S',     'BARSAD');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MOLE''S',       'MOLE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('ANOTHER''S',    'ANOTHER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MEN''S',        'MEN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WRITER''S',     'WRITER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('JURYMAN''S',    'JURYMAN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SMITH''S',      'SMITH');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('EARTH''S',      'EARTH');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MOMENT''S',     'MOMENT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LEADER''S',     'LEADER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('ARM''S',        'ARM');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('VACATION''S',   'VACATION');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SUITOR''S',     'SUITOR');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('OWL''S',        'OWL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('COUNTRYMAN''S', 'COUNTRYMAN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DARLING''S',    'DARLING');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CINDERELLA''S', 'CINDERELLA');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('FUNCTIONARY''S','FUNCTIONARY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('ANTOINE''S',    'ANTOINE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WOODSAWYER''S', 'WOODSAWYER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('NICK''S',       'NICK');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DEATH''S',      'DEATH');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('OTHER''S',      'OTHER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('PATIENT''S',    'PATIENT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('JERRY''S',      'JERRY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LORRY''S',      'LORRY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('PEOPLE''S',     'PEOPLE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MOTHER''S',     'MOTHER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WOMEN''S',      'WOMEN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SHOEMAKER''S',  'SHOEMAKER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MAKER''S',      'MAKER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CRUNCHER''S',   'CRUNCHER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('NATURE''S',     'NATURE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MONSEIGNEUR''S','MONSEIGNEUR');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('BOY''S',        'BOY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CROW''S',       'CROW');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SYDNEY''S',     'SYDNEY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CHILD''S',      'CHILD');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('TURNKEY''S',    'TURNKEY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HORSE''S',      'HORSE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SPEAKER''S',    'SPEAKER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('TOMORROW''S',   'TOMORROW');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LISTENER''S',   'LISTENER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GILES''S',      'GILES');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CAPTAIN''S',    'CAPTAIN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DOCTOR''S',     'DOCTOR');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('JUDGE''S',      'JUDGE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WIFE''S',       'WIFE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GENERAL''S',    'GENERAL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('STRYVER''S',    'STRYVER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CHARLES''S',    'CHARLES');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GOVERNOR''S',   'GOVERNOR');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SUFFERER''S',   'SUFFERER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('TRIBUNAL''S',   'TRIBUNAL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SOLDIER''S',    'SOLDIER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MAN''S',        'MAN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('RIDER''S',      'RIDER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LIFE''S',       'LIFE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MANETTE''S',    'MANETTE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('JOKER''S',      'JOKER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CUTLER''S',     'CUTLER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('PRISONER''S',   'PRISONER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MAJESTY''S',    'MAJESTY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MONSIEUR''S',   'MONSIEUR');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DEFARGE''S',    'DEFARGE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WHAT''S',       'WHAT');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CO''S',         'CO');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('ADVOCATE''S',   'ADVOCATE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('ENGLAND''S',    'ENGLAND');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MORNING''S',    'MORNING');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('PAUL''S',       'PAUL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('OFFENDER''S',   'OFFENDER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MADAME''S',     'MADAME');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('JOURNEY''S',    'JOURNEY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DOG''S',        'DOG');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('BLACKSMITH''S', 'BLACKSMITH');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('ANGEL''S',      'ANGEL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LION''S',       'LION');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HARM''S',       'HARM');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('COOK''S',       'COOK');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LORD''S',       'LORD');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('FAMILY''S',     'FAMILY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('BROTHER''S',    'BROTHER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('GIRL''S',       'GIRL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('COMPANY''S',    'COMPANY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('FARMER''S',     'FARMER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('COMPANION''S',  'COMPANION');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('LADY''S',       'LADY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DAUGHTER''S',   'DAUGHTER');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('JURY''S',       'JURY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('ONE''S',        'ONE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('FRIEND''S',     'FRIEND');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('DARNAY''S',     'DARNAY');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('WOMAN''S',      'WOMAN');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('BRIDE''S',      'BRIDE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('MINUTE''S',     'MINUTE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('CREATURE''S',   'CREATURE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HOUR''S',       'HOUR');
--
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('D''YE',    'DO YOU');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('HE''LL',   'HE WILL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('I''LL',    'I WILL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('I''VE',    'I HAVE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('SHE''LL',  'SHE WILL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('THEY''LL', 'THEY WILL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('YOU''LL',  'YOU WILL');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('YOU''RE',  'YOU ARE');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('YOU''VE',  'YOU HAVE');
--
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('O''CLOCK',   'O CLOCK');
INSERT INTO ABBREVIATED_WORD_SPLIT (Abbreviated_Word, Split_Words) Values ('D''AULNAIS', 'DE AULNAIS');
