
-- N (A+K+P)° (N-M)(F-E+H).((AxM)+F) W 000° (H-L).((DxG)-J)
-- N 51° 31.885 W 000° 07.455 
-- Assuming N 51 3(1/2) W 7

DROP   TABLE KC_CONNECTION_DEFGHJK PURGE;
CREATE TABLE KC_CONNECTION_DEFGHJK
AS
SELECT * FROM V_KC_CONNECTION_DEFGHJK WHERE A = 34
;

SELECT * FROM KC_CONNECTION_DEFGHJK;

BEGIN
   FOR LMNP_REC IN (SELECT LMNP FROM KC_CONNECTION_LMNP)
   LOOP
       INSERT INTO KC_CONNECTION_DEFGHJK  (A, D, E, F, G, H, J, K, L, M, N, P, DEFGHJK, LMNP,
                                           NORTH_DEGREE, NORTH_MINUTE_L1, NORTH_MINUTE_L2, NORTH_THOUSANDTH_MINUTE, 
                                           WEST_MINUTE, WEST_THOUSANDTH_MINUTE)
       SELECT A, D, E, F, G, H, J, K, L, M, N, P, DEFGHJK, LMNP, 
              NORTH_DEGREE, NORTH_MINUTE_L1, NORTH_MINUTE_L2, NORTH_THOUSANDTH_MINUTE, 
              WEST_MINUTE, WEST_THOUSANDTH_MINUTE
       FROM   V_KC_CONNECTION_DEFGHJK 
       WHERE  LMNP = LMNP_REC.LMNP 
       AND    DEFGHJK IN (SELECT FirstName FROM DICTIONARY.FIRST_NAME);
       
       COMMIT;
   END LOOP;
END;
/

SELECT * FROM KC_CONNECTION_DEFGHJK
ORDER BY WEST_THOUSANDTH_MINUTE;

