
-- N (A+K+P)° (N-M)(F-E+H).((AxM)+F) W 000° (H-L).((DxG)-J)
-- N 51° 31.885 W 000° 07.455 
-- Assuming N 51 32 W 7

DROP   TABLE KC_CONNECTION_LMNP PURGE;
CREATE TABLE KC_CONNECTION_LMNP
AS
SELECT Distinct L, M, N, P, 'xxxx' LMNP FROM   V_KC_CONNECTION_LMNP
/

UPDATE KC_CONNECTION_LMNP
SET    LMNP = substr('ABCDEFGHIJKLMNOPQRSTUVWXYZ', L, 1) ||
              substr('ABCDEFGHIJKLMNOPQRSTUVWXYZ', M, 1) ||
              substr('ABCDEFGHIJKLMNOPQRSTUVWXYZ', N, 1) ||
              substr('ABCDEFGHIJKLMNOPQRSTUVWXYZ', P, 1)
/
DELETE FROM  KC_CONNECTION_LMNP
WHERE  LMNP  NOT IN (SELECT LastName FROM DICTIONARY.LAST_NAME)
/

SELECT * FROM KC_CONNECTION_LMNP;

