
SELECT 32675 + 3 * (680 + 620 + 440 + 320 + 200) + 2 * (500 + 500)
FROM   DUAl
/

Create Table DI_CHECKSUM (
Line_Id    NUMBER,
HEX_TEXT   Varchar2(2) )
/

BEGIN
DELETE FROM DI_CHECKSUM;

INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (01, '2E');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (02, '42');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (03, '6C');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (04, '28');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (05, '65');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (06, '6E');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (07, '5C');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (08, '68');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (09, '15');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (10, '62');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (11, '64');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (12, '68');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (13, '68');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (14, '1A');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (15, '5E');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (16, '70');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (17, '57');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (18, '63');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (19, '6A');

INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (20, '6C');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (21, '59');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (22, '1A');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (23, '61');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (24, '50');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (25, '66');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (26, '62');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (27, '1F');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (28, '6F');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (29, '64');

INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (30, '66');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (31, '66');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (32, '5F');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (33, '74');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (34, '20');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (35, '62');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (36, '71');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (37, '15');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (38, '48');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (39, '2E');

INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (40, '2A');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (41, '20');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (42, '34');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (43, '39');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (44, '20');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (45, '2A');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (46, '55');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (47, '20');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (48, '2E');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (49, '2B');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (50, '2D');
INSERT INTO DI_CHECKSUM (Line_Id, HEX_TEXT)  Values (51, '2A');
END;
/

SELECT Count(*), Count(Distinct Line_Id) FROM DI_CHECKSUM;
SELECT Distinct substr(Hex_Text, 1, 1) FROM DI_CHECKSUM Order By 1;
SELECT Distinct substr(Hex_Text, 2, 1) FROM DI_CHECKSUM Order By 1;

-- 215
SELECT sum( instr('1234567890ABCDEF', Letter) ) FROM (
SELECT Line_Id, substr(Hex_Text, 1, 1) Letter FROM DI_CHECKSUM
) Order By 1;


-- 446
SELECT Sum( instr('1234567890ABCDEF', Letter) ) FROM (
SELECT Line_Id, substr(Hex_Text, 2, 1) Letter FROM DI_CHECKSUM
);

N 51 31.627   W 0 7.488
N 51 31.842   W 0 7.934
