
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N1'  ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N2'  ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N3'  ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N5'  ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N6'  ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N7'  ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N8'  ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N9'  ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N11' ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N12' ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N13' ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N14' ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N15' ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N16' ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N17' ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N18' ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N19' ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N20' ORDER BY FREQUENCY Desc;
SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG                        ORDER BY FREQUENCY;
SELECT  Variable, count(Distinct Number_Value)  FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG GROUP BY Variable ORDER BY 2;
/



CREATE OR REPLACE VIEW V_MAGNETISM_A AS (SELECT * FROM MAGNETISM_ORIG_A);
CREATE OR REPLACE VIEW V_MAGNETISM_B AS (SELECT * FROM MAGNETISM_ORIG_B);
CREATE OR REPLACE VIEW V_MAGNETISM_C AS (SELECT * FROM MAGNETISM_ORIG_C);
CREATE OR REPLACE VIEW V_MAGNETISM_D AS (SELECT * FROM MAGNETISM_ORIG_D);
CREATE OR REPLACE VIEW V_MAGNETISM_E AS (SELECT * FROM MAGNETISM_ORIG_E);
CREATE OR REPLACE VIEW V_MAGNETISM_F AS (SELECT * FROM MAGNETISM_ORIG_F);
CREATE OR REPLACE VIEW V_MAGNETISM_G AS (SELECT * FROM MAGNETISM_ORIG_G);
CREATE OR REPLACE VIEW V_MAGNETISM_H AS (SELECT * FROM MAGNETISM_ORIG_H);
CREATE OR REPLACE VIEW V_MAGNETISM_J AS (SELECT * FROM MAGNETISM_ORIG_J);
CREATE OR REPLACE VIEW V_MAGNETISM_K AS (SELECT * FROM MAGNETISM_ORIG_K);
/

SELECT  * FROM     MAGNETISM_ABCDEFGHJK_FREQ_ORIG WHERE Variable = 'N3'  ORDER BY Number_Value;
CREATE OR REPLACE VIEW V_MAGNETISM_E AS (SELECT * FROM MAGNETISM_ORIG_E WHERE N3 <= 11);

BEGIN 
    MAGNETISM_CONTROL.Reset;
END;
/
BEGIN 
    MAGNETISM_CONTROL.Set_Rows;
END;
/
-----------------------------------------------------------------------

CREATE OR REPLACE VIEW V_MAGNETISM_ABCDEFGHJK_FREQ
AS
SELECT 'N1'  Variable, N1  Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N1  UNION
SELECT 'N2'  Variable, N2  Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N2  UNION
SELECT 'N3'  Variable, N3  Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N3  UNION
SELECT 'N5'  Variable, N5  Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N5  UNION
SELECT 'N6'  Variable, N6  Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N6  UNION
SELECT 'N7'  Variable, N7  Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N7  UNION
SELECT 'N8'  Variable, N8  Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N8  UNION
SELECT 'N9'  Variable, N9  Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N9  UNION
SELECT 'N11' Variable, N11 Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N11 UNION
SELECT 'N12' Variable, N12 Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N12 UNION
SELECT 'N13' Variable, N13 Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N13 UNION
SELECT 'N14' Variable, N14 Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N14 UNION
SELECT 'N15' Variable, N15 Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N15 UNION
SELECT 'N16' Variable, N16 Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N16 UNION
SELECT 'N17' Variable, N17 Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N17 UNION
SELECT 'N18' Variable, N18 Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N18 UNION
SELECT 'N19' Variable, N19 Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N19 UNION
SELECT 'N20' Variable, N20 Number_Value, count(*) Frequency FROM  MAGNETISM_ABCDEFGHJK GROUP BY N20 
/

SELECT Variable, number_value, frequency, sum(1) OVER (PARTITION By Variable) Difff_Values
FROM   V_MAGNETISM_ABCDEFGHJK_FREQ
ORDER BY 4, 1, 2;

SELECT   Variable, to_char(sum(Frequency), '999,999,999,999') Tot
FROM     MAGNETISM_ABCDEFGHJK_FREQ
GROUP BY Variable
/

SELECT Segment_Name, Bytes / (1024 * 1024) Mb
FROM   USER_SEGMENTS
WHERE  Segment_Name Like '%MAG%'
ORDER BY 2 Desc
/

-------------------------------------------------------------------------------------------------------------

CREATE TABLE MAGNETISM_ABCDEFGHJK_FREQ_ORIG
AS
SELECT * FROM MAGNETISM_ABCDEFGHJK_FREQ;

TRUNCATE TABLE MAGNETISM_ABCDEFGHJK_FREQ;

