
CREATE TABLE QUAGMIRE_SOLUTION (
SOLUTION_ID       NUMBER,
PREV_SOLUTION_ID  NUMBER,
WORD_ID           NUMBER, 
DICTIONARY_ID     NUMBER
)
/

CREATE INDEX IDX_QUAG_SOL ON QUAGMIRE_SOLUTION (Solution_Id)
/